### ISSUE TITLE
error when using forint option

### ISSUE THREAD

**Issue by joostdekeijzer** [danott/ee-loopee#1]
Hi,

The plugin gives an error when using the 'forint' option.

The default 'foreach' value is set to NULL. The plugin first tries to loop through all foreach values resulting in an error. Setting the default value of 'foreach' to an empty array seems to work.

**Comment by notacouch** [comment]
Yeah I came across this problem, too, and as you said an empty array did the trick. 

This fork/commit shows the error and an easy fix in the meantime:
https://github.com/notacouch/ee-loopee/commit/e81c50ec6963035e59a7b1c18f2ac99f0bda4168

**Comment by danott** [comment]
@notacouch If you submit this as a pull request I'll merge it in and close the issue.

**Comment by notacouch** [comment]
Done. Sorry didn't notice this sooner.

https://github.com/danott/ee-loopee/pull/2

**Comment by danott** [comment]
Resolved with 60018f7739f5b5bb12c896470b6eb4c9f51f98ca
