### ISSUE TITLE
Escaping pipes in `foreach` problematic

### ISSUE THREAD

**Issue by CNG** [danott/ee-loopee#3]
Hello there, I might look into fixing this eventually, but for now I am just hard coding my form due to time constraints. 

It appears using escaped pipes in `foreach` only works if there aren't spaces in the values and the escaped pipes are after any colons when used with a colon in the `as` parameter.

This template code:

```
{exp:loopee
  foreach="date\|desc|edit_date\|desc|title\|asc"
  as="key"
  parse="inward"
}
<option value="{key}">{key}</option>{/exp:loopee}

{exp:loopee
  foreach="date\|desc:Created|edit_date\|desc:Modified|title\|asc:Title"
  as="key:val"
  parse="inward"
}
<option value="{key}">{val}</option>{/exp:loopee}

{exp:loopee
  foreach="Created:date\|desc|Modified:edit_date\|desc|Title:title\|asc"
  as="val:key"
  parse="inward"
}
<option value="{key}">{val}</option>{/exp:loopee}

{exp:loopee
  foreach="date\|desc:Date Created|edit_date\|desc:Date Modified|title\|asc:Title"
  as="key:val"
  parse="inward"
}
<option value="{key}">{val}</option>{/exp:loopee}

{exp:loopee
  foreach="Date Created:date\|desc|Date Modified:edit_date\|desc|Title:title\|asc"
  as="val:key"
  parse="inward"
}
<option value="{key}">{val}</option>{/exp:loopee}
```

Produces this output:

```
<option value="date|desc">date|desc</option>
<option value="edit_date|desc">edit_date|desc</option>
<option value="title|asc">title|asc</option>


<option value="0">date|desc:Created</option>
<option value="1">edit_date|desc:Modified</option>
<option value="2">title|asc:Title</option>


<option value="date|desc">Created</option>
<option value="edit_date|desc">Modified</option>
<option value="title|asc">Title</option>


<option value="0">date|desc:Date Created</option>
<option value="1">edit_date|desc:Date Modified</option>
<option value="2">title|asc:Title</option>


<option value="Date Created:date|desc">0</option>
<option value="Date Modified:edit_date|desc">1</option>
<option value="title|asc">Title</option>
```

**Comment by danott** [comment]
@CNG I don't have any EE projects I can try this out in right now. Can you test the branch https://github.com/danott/ee-loopee/tree/words_with_spaces and see if it fixes the issue. If so, I'll merge it into master.

**Comment by CNG** [comment]
Thank you, I’ll have to test tomorrow morning once I’m back on an IP from which I can access the environment I was using.

**Comment by CNG** [comment]
OK, so adding `\s` to the regex makes it allow for spaces in the values, which will allow me to use the plugin instead of hard coding the form.

The other half of the problem is still unresolved, but is less important for my case. If you want to use an escaped pipe, it must appear after the colon that separates variables for key/value. If you want an escaped pipe in both the key and value, then you're out of luck and still must hard code the output.

This template code:

```
{exp:loopee
  foreach="date\|desc:Date Created|title\|asc:Title"
  as="key:val"
  parse="inward"
}
<option value="{key}">{val}</option>{/exp:loopee}

{exp:loopee
  foreach="Date Created:date\|desc|Title:title\|asc"
  as="val:key"
  parse="inward"
}
<option value="{key}">{val}</option>{/exp:loopee}
```

Produces this output:

```
<option value="0">date|desc:Date Created</option>
<option value="1">title|asc:Title</option>


<option value="date|desc">Date Created</option>
<option value="title|asc">Title</option>
```

**Comment by danott** [comment]
Open a PR if you need to get that last bit working. Glancing at the code, it might be a little more involved.

**Comment by danott** [comment]
@CNG, by the way, thanks for verifying that change!

**Comment by CNG** [comment]
Yeah, that's why I decided to point it out to you first. At least it might be noted in the documentation for now. Perhaps I can take a look once I get this other work out of the way!

**Comment by danott** [comment]
Closing this issue after nearly two years of inactivity.
