### ISSUE TITLE
Nested loops don’t work

### ISSUE THREAD

**Issue by CNG** [danott/ee-loopee#5]
I assume this is a big undertaking, but I’d like to at least report that nesting Loopee tags does not give great results.

An example:

```
{exp:loopee parse="inward" foreach="A|B" as="a"}
  {exp:loopee parse="inward" foreach="1|2" as="b"}
    {exp:loopee parse="inward" foreach="a|b" as="c"}
      {a}{b}{c}
    {/exp:loopee}
  {/exp:loopee}
{/exp:loopee}
```

Output: `A1a B1a A2a B2a A1b B1b A2b B2b`

I pondered solving this by adding a prefix parameter, but I know little of EE plugin development, so while I got a prefix parameter working, it did not solve the problem and produced identical results. If you have any idea how to get this to work, or even a pointer, I’d love to hear it. Thanks!

For reference, since I don’t know where else to save this in case I should want it in the future, here is how I changed the plugin to add a prefix (only to the `foreach` section, not the `forint` section). I used PHP’s “variable variables” thinking the problem was something with variable overwriting, but that clearly was not it:

```
var $params = array(
  'prefix'    => NULL,
  ...
```

Then later:

```
/* TAG SETUP
 * Setup the custom defined "as" tags that are going to be replaced by either of the two loopee loops.
 */

$prefix = '';
if( isset($this->params['prefix']) ){
  $prefix = $this->params['prefix'];
}

// Assume the defaults, even if they do get reset, it's nice to be careful.
${$prefix.'key_regex'} = '/{loopee_key}/';
${$prefix.'value_regex'} = '/{loopee_value}/';
${$prefix.'count_regex'} = '/{loopee_count}/';

${$prefix.'params'} = $this->params;
${$prefix.'return_data'} = '';

/* If this is an array, the "as" parameter was a key:value pair.
 * Want to make sure we can replace both the key and the value appropriately */
if (is_array(${$prefix.'params'}['as']))
{
  /* Because there's no better way to get an anonymous-to-us array key,
   * just do a foreach even though there's (most likely) only one element. */
  foreach (${$prefix.'params'}['as'] as $key => $value)
  {
    ${$prefix.'key_regex'} = '/{('.($prefix?$prefix.':':'').$key.')}/';
    ${$prefix.'value_regex'} = '/{('.$value.')}/';
  }
}
/* There is no key assocated, the user is only replacing with a single value. Simply use the value */
else
{
  ${$prefix.'value_regex'} = '/{('.($prefix?$prefix.':':'').${$prefix.'params'}['as'].')}/';
}

${$prefix.'count_regex'} = '/{('.($prefix?$prefix.':':'').${$prefix.'params'}['count'].')}/';

/* FOREACH
 * Do the foreach bit for every single value that was piped.
 */
${$prefix.'loopee_count'} = 1;
foreach ((array)${$prefix.'params'}['foreach'] as $key => $value)
{
  // Replace all the {keys} and {values} in one fancy preg_replace.
  ${$prefix.'return_data'} .= preg_replace(
    array(
      ${$prefix.'key_regex'},
      ${$prefix.'value_regex'},
      ${$prefix.'count_regex'}
    ),
    array(
      $key,
      $value,
      ${$prefix.'loopee_count'}
    ),
    $tagdata
  );
  ${$prefix.'loopee_count'}++;
}

$this->return_data .= ${$prefix.'return_data'};
```

This allowed me to change my template code to:

```
{exp:loopee prefix="l1" parse="inward" foreach="A|B" as="a"}
  {exp:loopee prefix="l2" parse="inward" foreach="1|2" as="b"}
    {exp:loopee prefix="l3" parse="inward" foreach="a|b" as="c"}
      {l1:loopee_count}{l2:loopee_count}{l3:loopee_count}:{l1:a}{l2:b}{l3:c}
    {/exp:loopee}
  {/exp:loopee}
{/exp:loopee}
```

Which output: `111:A1a 211:B1a 121:A2a 221:B2a 112:A1b 212:B1b 122:A2b 222:B2b`

**Comment by danott** [comment]
I apologize for not responding to this in over two years. GitHub notifications slip through the cracks sometimes, and I'm just now doing a deep-dive in this new year.

I like the proposed API of "prefix" for differentiating the loops. It seems intuitive, and in-line with EE's templating.

Given the lack of activity on this issue in two years, there doesn't seem to be much demand for this feature? I'm going to close this for now, but we'll have the history of the idea if someone else finds themselves with a similar need!
